name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 2.2.207
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Test with dotnet
      run: dotnet test FunctionsSdkE2ETests.sln
