name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      matrix:
        dotnet: [ '2.2.207']

    steps:
    - uses: actions/checkout@v2
    - name: Test with dotnet
      run: dotnet test FunctionsSdkE2ETests.sln -v n